node('dind-node-1') {
 withMaven(maven:'M3') {
  stage('Checkout') {
   git url: 'https://github.com/piomin/sample-spring-cloud-comm.git', credentialsId: 'github-piomin',   branch: 'feign_with_discovery'
  }

  stage('Build') {
   dir('product-service') {
    sh 'mvn clean install'
   }
   def pom = readMavenPom file:'pom.xml'
   print pom.version
   env.version = pom.version
   currentBuild.description = "Release: ${env.version}"
  }

  stage('Image') {
   dir ('product-service') {
    def app = docker.build "piomin/product-service:${env.version}"
    //app.push()
   }
  }

  stage ('Run') {
   docker.image("piomin/product-service:${env.version}").run('-p 8093:8093 -m 256M -e EUREKA_DEFAULT_ZONE=http://discovery:8761/eureka -d --name product --network sample-spring-cloud-network')
  }

 }
}